/**
 * @fileoverview gRPC-Web generated client stub for example
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: example.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as example_pb from './example_pb'; // proto import: "example.proto"


export class ExampleServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorUnaryCall = new grpcWeb.MethodDescriptor(
    '/example.ExampleService/UnaryCall',
    grpcWeb.MethodType.UNARY,
    example_pb.Request,
    example_pb.Response,
    (request: example_pb.Request) => {
      return request.serializeBinary();
    },
    example_pb.Response.deserializeBinary
  );

  unaryCall(
    request: example_pb.Request,
    metadata?: grpcWeb.Metadata | null): Promise<example_pb.Response>;

  unaryCall(
    request: example_pb.Request,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: example_pb.Response) => void): grpcWeb.ClientReadableStream<example_pb.Response>;

  unaryCall(
    request: example_pb.Request,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: example_pb.Response) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/example.ExampleService/UnaryCall',
        request,
        metadata || {},
        this.methodDescriptorUnaryCall,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/example.ExampleService/UnaryCall',
    request,
    metadata || {},
    this.methodDescriptorUnaryCall);
  }

  methodDescriptorServerStreamingCall = new grpcWeb.MethodDescriptor(
    '/example.ExampleService/ServerStreamingCall',
    grpcWeb.MethodType.SERVER_STREAMING,
    example_pb.Request,
    example_pb.Response,
    (request: example_pb.Request) => {
      return request.serializeBinary();
    },
    example_pb.Response.deserializeBinary
  );

  serverStreamingCall(
    request: example_pb.Request,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<example_pb.Response> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/example.ExampleService/ServerStreamingCall',
      request,
      metadata || {},
      this.methodDescriptorServerStreamingCall);
  }

}

